### ISSUE TITLE
Displaying a button

### ISSUE THREAD

**Issue by mmorihiro** [MMorihiro/LearningTDD#2]
Scene2Dを使って何もしないボタンを一つ表示する。

**Comment by mmorihiro** [comment]
scene2d.uiはただ動かすだけでも
- uiskin.json
- default.fnt
- default.png
- uiskin.atlas
- uiskin.png  

が必要な模様。ない場合は例外が発生する。

**Comment by forestone23** [comment]
PRがmasterにマージされるまではOpenのままにするほうがいいと思うよ

**Comment by mmorihiro** [comment]
確かにコメントの継続性を重視するならそっちの方がいいかもね。
とりあえず考えていたのは、issueはプッシュする前に作れるから開発側が実装している間の思考を書いていき、そのissueをプルリクのときにレビュアーが参照するという感じ。
それだけならプルリクで会話する必要はないけど、その一方でプルリクはコードにコメントできるからレビュアーが使うと便利かなと思ったんだけど。

**Comment by forestone23** [comment]
そうだね。Issueはマージされる前は(一応)Openのままにしといて、マージするときにCloseするのがいいと思う。
本題から外れちゃうけど、PRのタイトルは`Displaying a button (Fix #2)`みたいにしたほうが、わかりやすい&Mergeした時に自動でIssueがCloseされるからいいと思う。

**Comment by mmorihiro** [comment]
なるほど。コミットメッセージをfixed #2 にすれば#2が閉じられるからそちらで行こうかと思っていたけど
プルリクで閉じられるならそれでもいいかもね。
issueを閉じるとその課題が終わったように見えてしまうけど、レビューも終わってマージした時にようやく終わりだからその時にissueを閉じられるのはより適してるね。

**Comment by mmorihiro** [comment]
この状態のissueはBoards上でReview/QAにすると分かりやすいと思う。
